name: fpm
description: Flutter Package Manager
version: 1.0.0
homepage: https://github.com/cesarferreira/fpm

environment:
  sdk: '>=2.8.1 <3.0.0'

executables:
  fpm: main
  
dependencies:
  path: ^1.7.0
  console: ^3.1.0
  cli_util: ^0.2.0
  http: ^0.12.1
  args: ^1.6.0
  ansicolor: ^1.0.2
  html: ^0.14.0+3


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
